const CHECK_INTERVAL = 500;
const TIMEOUT_DURATION = 2 * 60000;
const TIME_CLEAN_MSG = 30 * 60000;
const TTL = 300;
const HANDSHAKE = 'HANDSHAKE';
const DM = 'MESSAGE';
const PUBLIC_KEY_REQUEST = 'PUBLIC_KEY_REQUEST';
const PUBLIC_KEY_RESPONSE = 'PUBLIC_KEY_RESPONSE';
const TIMEOUT_ERROR_MESSAGE = `Neighbor check timed out after ${TIMEOUT_DURATION / 1000} seconds`;
const TIMEOUT_ERROR = 'TIMEOUT_ERROR';
const DEFAULT_TIMEOUT = 10000;
module.exports = {
  PUBLIC_KEY_REQUEST,
  PUBLIC_KEY_RESPONSE,
  HANDSHAKE,
  DEFAULT_TIMEOUT,
  TIMEOUT_ERROR,
  TIME_CLEAN_MSG,
  CHECK_INTERVAL,
  TIMEOUT_DURATION,
  TIMEOUT_ERROR_MESSAGE,
  TTL,
  DM,
};
