const CHECK_INTERVAL = 500;
const TIMEOUT_DURATION = 2 * 60000;
const TIME_CLEAN_MSG = 30 * 60000;
const TTL = 300;
const HANDSHAKE = 'HANDSHAKE';
const DM = 'MESSAGE';
const TIMEOUT_ERROR_MESSAGE = `Neighbor check timed out after ${TIMEOUT_DURATION / 1000} seconds`;

module.exports = {
  HANDSHAKE,
  TIME_CLEAN_MSG,
  CHECK_INTERVAL,
  TIMEOUT_DURATION,
  TIMEOUT_ERROR_MESSAGE,
  TTL,
  DM,
};
